FROM python:3

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip
RUN pip install ptvsd==4.1.3
COPY requirements.txt ./
RUN pip install -r requirements.txt 

COPY . .

CMD [ "python3", "-u", "./main.py" ]