FROM python:3.7-slim-buster

# multiarch/ubuntu-core:x86_64-bionic

ENV DEBIAN_FRONTEND=noninteractive 

WORKDIR /app

RUN apt-get update -y 
RUN apt-get install -y apt-utils \
        software-properties-common \
        freetds-bin \
        unixodbc \
        openssh-client \
        sshpass \
        sudo \
        openvpn \
        net-tools \
        ifupdown \
        git \
        jq \
        nano \
        dnsutils 
        
# have to be run alone to run
RUN apt-get install -y bsdmainutils vim

#########################################################
#                   PYTHON CONFIG                       #
#########################################################
RUN apt-get update -y && \
    apt-get install -y python3-pip python3-dev
    
RUN apt install python3-pip
RUN pip3 install ansible requests azure.iot.device


#########################################################
#		     PyODBC                             #
#########################################################
        
# apt-get and system utilities
RUN apt-get update && apt-get install -y \
    curl apt-utils apt-transport-https debconf-utils gcc build-essential \
    && rm -rf /var/lib/apt/lists/*
    
# adding custom Microsoft repository
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# install SQL Server drivers
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

# install SQL Server tools
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"

# install necessary locales, this prevents any locale errors related to Microsoft packages
RUN apt-get update && apt-get install -y locales \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen
    
# copy requirements and install packages, I added this for general use
COPY ./requirements.txt  ./
RUN pip3 install -r ./requirements.txt
# you can also use regular install of the packages
RUN pip3 install pyodbc SQLAlchemy


#########################################################
#                   AZURE CONFIG                        #
#########################################################
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN az extension add --name azure-iot
#deprecated: RUN az extension add --name azure-cli-iot-ext

RUN az login -u lorenzo.caseri@regaslab.com -p Regas2020

#########################################################
#                   envsubst                            #
#########################################################

RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
RUN chmod +x envsubst
RUN mv envsubst /usr/local/bin


#########################################################
#                   COPY FILES                          #
#########################################################

COPY . .

CMD [ "python3", "-u", "./main.py" ]
