FROM python:3.7-slim-buster

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

#########################################################
#                   COPY FILES                          #
#########################################################

COPY requirements.txt ./
RUN pip install -r requirements.txt


COPY . .

CMD [ "python3", "-u", "./main.py" ]
