FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

COPY qemu-arm-static /usr/bin

COPY requirements.txt ./
RUN apt-get update && apt-get -y install gcc libpq-dev build-essential
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]